name: Auto Merge after CodeQL

on:
  workflow_run:
    workflows: ["CodeQL Advanced"]
    types:
      - completed

jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get PR info
        id: get-pr
        uses: actions/github-script@v7
        with:
          script: |
            const headBranch = context.payload.workflow_run.head_branch;

            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${headBranch}`,
              state: 'open'
            });

            if (prs.data.length === 0) {
              console.log(`🔍 No open pull request found for branch: ${headBranch}. Skipping auto-merge.`);
              core.setOutput("should_merge", "false");
            } else {
              const pr = prs.data[0];
              console.log(`✅ Found PR #${pr.number}`);
              core.setOutput("should_merge", "true");
              core.setOutput("pr_number", pr.number);
              core.setOutput("head_branch", pr.head.ref);
            }

      - name: Enable Auto-Merge
        if: steps.get-pr.outputs.should_merge == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.BOT_PAT }}
          pull-request-number: ${{ steps.get-pr.outputs.pr_number }}
          merge-method: squash

      - name: Comment on PR
        if: steps.get-pr.outputs.should_merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt("${{ steps.get-pr.outputs.pr_number }}"),
              body: "🤖 This PR is automatically merged and closed."
            });
        
      - name: Wait for merge to complete
        if: steps.get-pr.outputs.should_merge == 'true'
        run: sleep 20  # wait a bit for GitHub to merge

      - name: Delete branch if merged
        if: steps.get-pr.outputs.should_merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = parseInt("${{ steps.get-pr.outputs.pr_number }}");
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            if (pr.data.merged) {
              const ref = `heads/${pr.data.head.ref}`;
              console.log(`🧹 Deleting merged branch: ${ref}`);
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: ref
              });
            } else {
              console.log("⏳ PR is not merged yet, skipping branch deletion.");
            }