name: Auto Merge Pull Request

on:
  workflow_run:
    workflows: ["CodeQL Advanced"]
    types:
      - completed

jobs:
  auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Info
        id: get-pr
        uses: actions/github-script@v7
        with:
          script: |
            const headBranch = context.payload.workflow_run.head_branch;

            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${headBranch}`,
              state: 'open'
            });

            if (prs.data.length === 0) {
              core.setFailed(`No open pull request found for branch: ${headBranch}`);
            } else {
              const pr = prs.data[0];
              console.log(`Found PR #${pr.number}`);
              core.setOutput("pr_number", pr.number);
            }

      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.BOT_PAT }}
          pull-request-number: ${{ steps.get-pr.outputs.pr_number }}
          merge-method: squash
